name: square_in_app_payments_example
description: Demonstrates how to use the square_in_app_payments plugin.

version: 1.0.0+1

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  http: any

dev_dependencies:
  square_in_app_payments:
    path: ../

flutter:
  uses-material-design: true

  assets:
    - assets/
  fonts:
    - family: SF_Pro_Text
      fonts:
        - asset: fonts/sf_pro_text_bold.otf
          weight: 700
        - asset: fonts/sf_pro_text_medium.otf
          weight: 500
        - asset: fonts/sf_pro_text_regular.otf
        - asset: fonts/sf_pro_text_semibold.otf
          weight: 600
