name: square_in_app_payments
description: A flutter plugin for suqare in-app payments SDK.
version: 1.0.0
authors:
- Xiao Hu <xiao@squareup.com>
- John Austin <jaustin@squareup.com>
- Stephen Josey <sjosey@squareup.com>
homepage: https://github.com/square/in-app-payments-flutter-plugin

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  built_value: "^6.1.5"

dev_dependencies:
  build:
  build_runner:
  source_gen:
  built_value_generator:

# The following section is specific to Flutter.
flutter:
  plugin:
    androidPackage: sqip.flutter
    pluginClass: SquareInAppPaymentsFlutterPlugin